Repository spacetelescope/STScI-STIPS, pull requests merged in 2020-05, with the labels that each got.

#65 Remove old tests and init testing infrastructure
  .travis.yml
  docs/Makefile
  docs/_themes/theme_webbpsf/globaltoc.html
  docs/_themes/theme_webbpsf/layout.html
  docs/_themes/theme_webbpsf/localtoc.html
  docs/_themes/theme_webbpsf/searchbox.html
  docs/_themes/theme_webbpsf/static/astropy_linkout_20.png
  docs/_themes/theme_webbpsf/static/astropy_logo.ico
  docs/_themes/theme_webbpsf/static/astropy_logo_32.png
  docs/_themes/theme_webbpsf/static/bootstrap-astropy.css
  docs/_themes/theme_webbpsf/static/bootstrap-webbpsf.css
  docs/_themes/theme_webbpsf/static/sidebar.js
  docs/_themes/theme_webbpsf/static/webbpsf_logo_32.png
  docs/_themes/theme_webbpsf/theme.conf
  docs/conf.py
  docs/wfirst_figures/compare_wfi_sca09_sca17.png
  docs/wfirst_figures/field_layout.png
  docs/wfirst_figures/fig_cgi_spc_f770.png
  docs/wfirst_figures/webbpsf-wfirst_page_header.png
  environment.yml
  examples/example.py
  stips/__init__.py
  stips/_astropy_init.py
  stips/astro_image/__init__.py
  stips/astro_image/tests/__init__.py
  stips/astro_image/tests/test_AstroImage.py
  stips/astro_image/tests/test_add_points.py
  stips/astro_image/tests/test_wcs.py
  stips/data/CreatePhoenixGrid.py
  stips/observation_module/tests/test_ObservationModule.py
  stips/scene_module/scene_module.py
  stips/scene_module/tests/test_SceneModule.py
  stips/utilities/tests/test_convolve.py
Labels: Ready For Review, Testing

#71 update docs to show how to download STIPS data
  docs/installation.rst
Labels: Data, Documentation, Ready For Review

#67 Initial set of tests
  .travis.yml
  stips/__init__.py
  stips/astro_image/astro_image.py
  stips/astro_image/tests/__init__.py
  stips/astro_image/tests/test_AstroImage.py
  stips/astro_image/tests/test_add_points.py
  stips/astro_image/tests/test_wcs.py
  stips/conftest.py
  stips/data/__init__.py
  stips/tests/__init__.py
  stips/tests/test_wfirst.py
  stips/utilities/testing.py
Labels: Ready For Review, Testing

#74 Remove AstroPy features from conftest.py
  stips/conftest.py
Labels: Ready For Review, Testing

#78 Make veryslow marker tests optional on CI
  .travis.yml
Labels: Ready For Review

#77 Add PSF grid and non-memmapped calculations
  .travis.yml
  setup.cfg
  stips/astro_image/astro_image.py
  stips/astro_image/tests/test_AstroImage.py
  stips/astro_image/tests/test_wcs.py
  stips/instruments/instrument.py
  stips/instruments/miri.py
  stips/instruments/nircam.py
  stips/instruments/wfc3ir.py
  stips/instruments/wfi.py
  stips/observation_module/observation_module.py
  stips/stellar_module/star_generator.py
  stips/tests/test_wfirst.py
  stips/utilities/testing.py
  stips/utilities/utilities.py
Labels: Priority-High, Ready For Review

#69 v1.0.8 Release
  CHANGES.rst
  Dockerfile
  dev/conda_envs/environment_v1.0.7.yml
  dev/conda_envs/environment_v1.0.8.yml
  docs/installation.rst
  setup.cfg
  stips/__init__.py
  stips/astro_image/__init__.py
  stips/astro_image/astro_image.py
  stips/data/CreatePhoenixGrid.py
  stips/instruments/wfi.py
  stips/utilities/utilities.py
  stips/version/__init__.py
Labels: Release Preparation, WIP

#84 Add psf=False whenever a non-data AstroImage is being created
  stips/astro_image/tests/test_AstroImage.py
  stips/astro_image/tests/test_add_points.py
  stips/astro_image/tests/test_wcs.py
  stips/instruments/instrument.py
  stips/observation_module/observation_module.py
  stips/tests/test_wfirst.py
Labels: Bug, Ready For Review
